# Generated by Django 4.2 on 2023-04-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_phone_number', models.CharField(max_length=255, null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('estimate_year_of_graduation', models.IntegerField(default=None)),
                ('specialisation', models.CharField(choices=[('Team Captain', 'Team Captain'), ('Chief Engineer', 'Chief Engineer'), ('Aerodynamics', 'Aerodynamics'), ('Powertrain', 'Powertrain'), ('Chassis', 'Chassis'), ('Engine', 'Engine'), ('Electronics & Wiring', 'Electronics & Wiring'), ('Suspension', 'Suspension'), ('IT', 'IT'), ('Team Member', 'Team Member'), ('Manufacturing', 'Manufacturing')], max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.students')),
            ],
        ),
    ]
