# Generated by Django 4.2 on 2023-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_students_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='estimate_year_of_graduation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
