# Generated by Django 4.2 on 2024-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_students_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='nationality',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='rating',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='driver',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='eso',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='role_at_competition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='role_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
