# Generated by Django 4.2 on 2024-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_nationality_students_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='specialisation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
