# Generated by Django 4.2 on 2023-04-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('car_number', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=255, null=True)),
                ('competition', models.ForeignKey(blank=True, db_column='competition_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competition.competitions')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('mobile_phone_number', models.CharField(max_length=255, null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('study', models.CharField(max_length=255, null=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('estimate_year_of_graduation', models.IntegerField(default=None)),
                ('role_in_the_team', models.CharField(choices=[('Team Captain', 'Team Captain'), ('Chief Engineer', 'Chief Engineer'), ('Aerodynamics', 'Aerodynamics'), ('Powertrain', 'Powertrain'), ('Chassis', 'Chassis'), ('Engine', 'Engine'), ('Electronics & Wiring', 'Electronics & Wiring'), ('Suspension', 'Suspension'), ('IT', 'IT'), ('Team Member', 'Team Member'), ('Manufacturing', 'Manufacturing')], max_length=255, null=True)),
                ('role_at_the_competition', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='competition.teams')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
