# Generated by Django 4.2 on 2023-04-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_students_order'),
        ('competition', '0003_alter_competitionstudents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionstudents',
            name='student',
            field=models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_students', to='accounts.students'),
        ),
    ]
